### ISSUE TITLE
It cannot encode large files

### ISSUE THREAD

**Issue by mehran-develop** [quasarstream/PHP-FFmpeg-video-streaming#142]
It cannot encode files with a size of 500 MB and 1 GB
Do you have a solution? I even use a dedicated server

`$config = [
                'ffmpeg.binaries'  => 'C:\ffmpeg\bin\ffmpeg.exe',
                'ffprobe.binaries' => 'C:\ffmpeg\bin\ffprobe.exe',
                'timeout'          => $time * 3600, // The timeout for the underlying process
                'ffmpeg.threads'   => 24,   // The number of threads that FFmpeg should use
            ];`

            $video->hls()
                ->encryption($save_to, $url, 1)
                    ->setHlsTime(40)
                ->setFormat($format)
                ->addRepresentation((new Representation())->setKiloBitrate(2048)->setResize(1280, 720))
                ->save(public_path('data/' . $main_folder . '/' . $sub_folder . '/code/' . $name));

if file size 500 MB after 3 min process kill in terminal

**Comment by crishoj** [comment]
@mehran-develop did you discover the reason for the configured timeout not being effective?
